Update build.yml, checking error

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,6 +36,11 @@ jobs:
         working-directory: /home/runner/work/Final-Project/Final-Project/tests
         run: |
           ./run_test.sh ./hello_world1 ../build/Banana ../hws/hello_world1.slug
+          echo "Return code: $?"
+          if [ $? -ne 0 ]; then
+            echo "Test hello_world1 failed"
+            exit 1
+          fi
 
       - name: Run hello_world2
         working-directory: /home/runner/work/Final-Project/Final-Project/tests
